# Generated by Django 4.1.7 on 2023-03-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_internee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internee',
            old_name='area',
            new_name='area_of_interest',
        ),
    ]
